version: "2"

services:
  quiz-ui:
    build: ./quiz-ui/.
    environment:
      - SERVICE_NAME=quiz-ui
      - API_HOST=quiz-api
      - API_PORT=3030
    ports:
      - "80:3000"
    networks:
      - frontend
      - backend

  quiz-api:
    build: ./quiz-api/.
    environment:
      - QUIZ_API_HOST=quiz-api-db
      - QUIZ_API_PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3030:3030"
    networks:
     backend:
      aliases:
       - quiz-api

  quiz-api-db:
    build: ./quiz-api-db/.
    ports:
      - "5000:5000"
    networks:
      - backend

  quiz-worker:
    build: ./quiz-worker/.
    environment:
      - QUIZ_API_HOST=quiz-api-db
      - QUIZ_API_PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - backend

  redis:
    image: hypriot/rpi-redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  frontend:
  backend:
