version: "2"

services:
  quiz-ui:
    build: ./quiz-ui/.
    ports:
      - "3000:3000"
    networks:
      - front-tier
      - back-tier

  quiz-api:
    build: ./quiz-api/.
    ports:
      - "3030:3030"
    links:
      - redis
    networks:
      - back-tier

  quiz-api-db:
    build: ./quiz-api-db/.
    ports:
      - "5000:5000"
    networks:
      - back-tier

  redis:
    image: redis
    ports: ["6379"]
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:
