ui:
 build: ./quiz-ui/.
 ports:
  - 80:3000
 links:
  - api

api:
 build: ./quiz-api/.
 ports:
  - 3030:3030
 links:
  - apidb
  - redis

apidb:
 build: ./quiz-api-db/.
 ports:
  - 5000:5000

redis:
  image: redis
  ports:
  - 6379:6379
